name: Build test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04, windows-2019]
        include:
          - os: macos-10.15
            BUILD_COMMAND: cargo build --features metal
          - os: ubuntu-18.04
            BUILD_COMMAND: cargo build --features vulkan
          - os: windows-2019
            BUILD_COMMAND: cargo build --features dx12
    steps:
    - uses: actions/checkout@v2
    - name: Build on ${{ matrix.os }}
      run: ${{ matrix.BUILD_COMMAND }}
