name: Build test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [
          iOS Metal,
          MacOS Metal,
          Ubuntu Vulkan,
          Windows DirectX 12,
        ]
        include:
          - os: macos-10.15
            name: iOS Metal
            BUILD_COMMAND: rustup target add aarch64-apple-ios; cargo build --example ocean_ios --features metal --target aarch64-apple-ios
            TARGET_BUILD: aarch64-apple-ios
          - os: macos-10.15
            name: MacOS Metal
            BUILD_COMMAND: cargo build --features metal
            TARGET_BUILD: macos
          - os: ubuntu-18.04
            name: Ubuntu Vulkan
            BUILD_COMMAND: cargo build --features vulkan
            TARGET_BUILD: linux
          - os: windows-2019
            name: Windows DirectX 12
            BUILD_COMMAND: cargo build --features dx12
            TARGET_BUILD: windows
    steps:
    - uses: actions/checkout@v2
    - name: Build on ${{ matrix.TARGET_BUILD }}
      run: ${{ matrix.BUILD_COMMAND }}
